import crypto from 'node:crypto';
import { Router } from 'express';
import { query } from '../db.js';
import { requireAuth, loadBillAccess } from '../auth.js';
import { logAudit } from '../lib/audit.js';

const router = Router();
const wrap = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);

// --- Organizer-managed secure links --------------------------------------

router.get('/bills/:id/shares', requireAuth, wrap(async (req, res) => {
  const access = await loadBillAccess(req.user.id, Number(req.params.id));
  if (!access) return res.status(404).json({ error: 'Bill not found' });
  const { rows } = await query(
    'SELECT * FROM share_links WHERE bill_id = $1 ORDER BY created_at DESC',
    [access.bill.id],
  );
  res.json({ shares: rows });
}));

router.post('/bills/:id/shares', requireAuth, wrap(async (req, res) => {
  const access = await loadBillAccess(req.user.id, Number(req.params.id));
  if (!access) return res.status(404).json({ error: 'Bill not found' });
  if (!access.isOwner) return res.status(403).json({ error: 'Only the organizer can create share links' });
  const { expiresInDays, includeCharges } = req.body || {};
  const token = crypto.randomBytes(18).toString('base64url');
  const expiresAt = expiresInDays
    ? new Date(Date.now() + Number(expiresInDays) * 24 * 60 * 60 * 1000)
    : null;
  const scope = { includeCharges: Boolean(includeCharges) };
  const { rows } = await query(
    `INSERT INTO share_links (id, bill_id, created_by, scope, expires_at)
     VALUES ($1, $2, $3, $4, $5) RETURNING *`,
    [token, access.bill.id, req.user.id, JSON.stringify(scope), expiresAt],
  );
  await logAudit({
    groupId: access.bill.group_id,
    billId: access.bill.id,
    actorId: req.user.id,
    action: 'share.created',
    detail: { token: rows[0].id, expiresAt },
  });
  res.status(201).json({ share: rows[0] });
}));

router.post('/shares/:shareId/revoke', requireAuth, wrap(async (req, res) => {
  const { rows: shareRows } = await query('SELECT * FROM share_links WHERE id = $1', [req.params.shareId]);
  if (shareRows.length === 0) return res.status(404).json({ error: 'Link not found' });
  const share = shareRows[0];
  const access = await loadBillAccess(req.user.id, share.bill_id);
  if (!access || !access.isOwner) return res.status(403).json({ error: 'Only the organizer can revoke a link' });
  const { rows } = await query('UPDATE share_links SET revoked = true WHERE id = $1 RETURNING *', [share.id]);
  await logAudit({
    groupId: access.bill.group_id,
    billId: access.bill.id,
    actorId: req.user.id,
    action: 'share.revoked',
    detail: { token: share.id },
  });
  res.json({ share: rows[0] });
}));

// --- Public read-only view -----------------------------------------------

router.get('/share/:token', wrap(async (req, res) => {
  const { rows } = await query('SELECT * FROM share_links WHERE id = $1', [req.params.token]);
  if (rows.length === 0) return res.status(404).json({ error: 'This link is not valid' });
  const share = rows[0];
  if (share.revoked) return res.status(410).json({ error: 'This link has been revoked' });
  if (share.expires_at && new Date(share.expires_at) < new Date()) {
    return res.status(410).json({ error: 'This link has expired' });
  }

  const billRes = await query('SELECT * FROM bills WHERE id = $1', [share.bill_id]);
  const bill = billRes.rows[0];
  const groupRes = await query('SELECT name, provider, currency FROM groups WHERE id = $1', [bill.group_id]);
  const group = groupRes.rows[0];
  const allocation = await query(
    'SELECT * FROM allocations WHERE bill_id = $1 ORDER BY id DESC LIMIT 1',
    [bill.id],
  );

  let totals = [];
  if (allocation.rows.length > 0) {
    const items = await query(
      `SELECT ai.total_cents, ai.shared_cents, ai.personal_cents, m.name
         FROM allocation_items ai JOIN members m ON m.id = ai.member_id
        WHERE ai.allocation_id = $1 ORDER BY m.is_owner DESC, m.id ASC`,
      [allocation.rows[0].id],
    );
    totals = items.rows.map((i) => ({
      name: i.name,
      totalCents: Number(i.total_cents),
      sharedCents: Number(i.shared_cents),
      personalCents: Number(i.personal_cents),
    }));
  }

  const scope = share.scope || {};
  res.json({
    provider: group.provider,
    group: { name: group.name },
    bill: {
      period_label: bill.period_label,
      due_date: bill.due_date,
      statement_date: bill.statement_date,
      provider_total_cents: Number(bill.provider_total_cents),
      currency: group.currency,
    },
    totals: scope.includeCharges === false ? [] : totals,
    sharedAt: share.created_at,
    note: 'This is a shared summary generated by BillShare. Amounts are household splits, not carrier charges.',
  });
}));

export default router;
